name: Selenium Cucumber Tests

on: push

jobs:
  Selenium-Cucumber-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Baixar e configurar o Microsoft Edge WebDriver
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          gpg --no-default-keyring --keyring ./microsoft-keyring.gpg --import ./microsoft.gpg
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge-dev.list
          sudo mv ./microsoft-keyring.gpg /usr/share/keyrings/microsoft-archive-keyring.gpg
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-dev

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use a versão adequada do Node.js

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run run:test:cucumber

      - name: generate report
        if: ${{always()}}
        run: npm run generate:MultipleHtml:report

        
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report