name: Selenium Tests with Microsoft Edge

on: [push] # You can customize the trigger event(s) here

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Microsoft Edge
      run: |
        curl -O https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_$(curl -s https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/ | grep -oP '(?<=href=")[^_]+[0-9]+\.[0-9]+\.[0-9]+[^"]+' | sort -V | tail -1)_amd64.deb
        sudo dpkg -i microsoft-edge-dev*.deb
        sudo apt-get install -f

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Set to your desired Node.js version

    - name: Install Dependencies
      run: npm install
        
    - name: Run Selenium Tests
      run: node teste.js