name: Selenium Tests with Microsoft Edge

on: [push] # You can customize the trigger event(s) here

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and config Microsoft Edge WebDriver
      run: |
        wget https://msedgedriver.azureedge.net/115.0.1901.203/edgedriver_linux64.zip -O msedgedriver_linux64.zip
        unzip msedgedriver_linux64.zip
        chmod +x msedgedriver
        sudo mv msedgedriver /usr/local/bin/

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Set to your desired Node.js version

    - name: Install Dependencies
      run: npm install
        
    - name: Run Selenium Tests
      run: node teste.js