name: Selenium Tests with Microsoft Edge

on: [push] # You can customize the trigger event(s) here

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download and config Microsoft Edge WebDriver
      run: |
        wget https://msedgedriver.azureedge.net/115.0.1901.203/edgedriver_linux64.zip -O msedgedriver_linux64.zip
        unzip msedgedriver_linux64.zip
        chmod +x msedgedriver
        sudo mv msedgedriver /usr/local/bin/

    - name: Install all dependencies
      run: npm install -y

    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Run Selenium Tests
      run: npm run run:test:cucumber

    - name: Genrate report Selenium Tests
      if: ${{ always() }}
      run: npm run generate:MultipleHtml:report

    - name: Deploy report page
      uses: peaceiris/actions-gh-pages@v3

      if: ${{ always() && github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./report